language: go

go:
   - 1.1
   - 1.2
   - tip

install:
   - go get code.google.com/p/go.tools/cmd/cover
   - go get github.com/modocache/gover
   - go get github.com/mattn/goveralls
   - PATH=$PATH:$HOME/gopath/bin

script:
   - go test ./...
   - gover

after_success:
   - goveralls -coverprofile=gover.coverprofile -service=travis-ci
